- name: Validate node_exporter_action_list
  ansible.builtin.assert:
    that:
      - node_exporter_actions is defined
      - node_exporter_actions is string
      - node_exporter_actions | length > 0

- name: Create node_exporter_action_list
  ansible.builtin.set_fact:
    node_exporter_action_list: "{{ node_exporter_actions.split(',') }}"

- name: Validate node_exporter_action_list
  ansible.builtin.assert:
    that:
      - node_exporter_action_list | length > 0
      - node_exporter_action_list | difference(node_exporter_supported_actions) | length == 0

- name: Deploy Node Exporter
  ansible.builtin.include_tasks: "{{ task_name }}.yml"
  loop: "{{ node_exporter_action_list }}"
  loop_control:
    loop_var: task_name
